### ISSUE TITLE
Vulnerability to absence of retiring r-spatial packages

### ISSUE THREAD

**Issue by rsbivand** [edzer/trajectories#29]
[00check.log](https://github.com/edzer/trajectories/files/11141495/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path.

Do you have a view on what to do with this package and `spacetime`? Are they candidates for retirement too?

**Comment by edzer** [comment]
Now on CRAN.
